services:
  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./conf/redis.conf:/etc/redis.conf
    env_file:
      - ./.env
    restart: always

volumes:
  redis-data: